### ISSUE TITLE
HTML autocomplete doesn't work

### ISSUE THREAD

**Issue by budparr** [mattstratton/language-hugo#6]
language-hugo 0.2.0

1) Open an HTML document
2) type `div` + tab
3) Nothing happens
 
Expected autocomplete of the div to ouput an opening and closing div with a class, which I believe is a default for Atom.

~~I started researching this a bit (and if I can I'll finish later) and think there needs to be some specificity on lines 8-10 of the hugo grammar:  https://github.com/mattstratton/language-hugo/blob/master/grammars/hugo.cson#L8-L10 Compare the [Jekyll highlight](https://github.com/gkemmey/jekyll-syntax-highlighting/blob/master/grammars/jekyll-syntax-highlighting.cson#L487-L503
)~~

**Comment by budparr** [comment]
I haven't figured this out, but it does appear to be a conflict with https://atom.io/packages/autocomplete-plus

**Comment by mattstratton** [comment]
I've noticed the same behavior; I'll check to see if I have the same autocomplete plugin.

**Comment by williampansky** [comment]
Any updates on this issue? I love the highlighting, but the lack of autocomplete is kind of a drag.

**Comment by ghost** [comment]
Tried debugging it but got distracted by groestl moon. Logging cursor scope gives me `source.hugo` and no matter what I tried no luck (but I didn't try `--safe` mode).

Only way I can get the autocomplete on is to <kbd>Sift-Ctrl-L</kbd> and flip into HTML. I've been putting up without autocompletion because I really like the syntax highlighting. I wish we could figure out what's going on here.

Here's the grammar rewritten in JSON. The more common syntax of JSON makes it easier to validate and modify given its ubiquity and support within the development community. Enjoy.

**Note:** Some of the RegExp may have gotten borked in conversion—I did not carefully check it.

<details>
<summary>Click to expand JSON</summary>
<pre><code>{
  "fileTypes": [
    "md",
    "html"
  ],
  "foldingStartMarker": "({{(.*)range(.*)}})|({{(.*)if(.*))",
  "foldingStopMarker": "({{(.*)end(.*)}})",
  "name": "Hugo",
  "patterns": [
    {
      "include": "text.html.basic"
    },
    {
      "include": "source.gfm"
    },
    {
      "begin": "{{<|{{%",
      "beginCaptures": {
        "0": {
          "name": "punctuation.section.embedded.begin.hugo"
        }
      },
      "end": ">}}|%}}",
      "endCaptures": {
        "0": {
          "name": "punctuation.section.embedded.end.hugo"
        }
      },
      "patterns": [
        {
          "match": "\\b([^\\s^\\\"]+)\\b",
          "name": "support.function.hugo"
        }
      ]
    },
    {
      "begin": "{{\\/\\*",
      "end": "\\*\\/}}",
      "name": "comment.block.hugo"
    },
    {
      "begin": "{{-|{{",
      "beginCaptures": {
        "0": {
          "name": "punctuation.section.embedded.begin.hugo"
        }
      },
      "end": "}}|-}}",
      "endCaptures": {
        "0": {
          "name": "punctuation.section.embedded.end.hugo"
        }
      },
      "patterns": [
        {
          "match": "\\b(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))\\b",
          "name": "constant.numeric.hugo"
        },
        {
          "match": "\\b(if|else|range|template|with|end|nil|define|where)\\b",
          "name": "keyword.control.hugo"
        },
        {
          "match": "\\b(and|call|html|index|js|len|not|or|print|printf|println|urlquery|eq|ne|lt|le|gt|ge)\\b",
          "name": "support.function.builtin.gotemplate"
        },
        {
          "begin": "\\$\\.",
          "end": "\\s",
          "name": "support.function.builtin.hugo"
        },
        {
          "match": "[.$][\\w]*",
          "name": "variable.hugo"
        },
        {
          "match": ":=",
          "name": "keyword.operator.initialize.hugo"
        },
        {
          "match": "\\b(add|delimit|dict|slice|shuffle|echoParam|eq|first|jsonify|last|after|getenv|in|intersect|isset|seq|sort|where|readDir|readFile|imageConfig|int|printf|chomp|dateFormat|emojify|highlight|htmlEscape|htmlUnescape|humanize|lower|markdownify|plainify|pluralize|findRE|replace|replaceRE|safeHTML|safeHTMLAttr|safeCSS|safeJS|singularize|slicestr|truncate|split|string|substr|hasPrefix|title|trim|upper|countwords|countrunes|md5|sha1|sha256|i18n|time|now|absLangURL|relLangURL|absURL|relURL|ref|relref|safeURL|urlize|querify|apply|base64Encode|base64Decode|modBool)\\b",
          "name": "support.function.builtin.hugo"
        },
        {
          "begin": "'",
          "end": "'",
          "name": "string.quoted.single.hugo"
        },
        {
          "begin": "\"",
          "end": "\"",
          "name": "string.quoted.single.hugo"
        }
      ]
    },
    {
      "begin": "^\\+\\+\\+$",
      "beginCaptures": {
        "0": {
          "name": "punctuation.section.embedded.begin.hugo"
        }
      },
      "end": "^\\+\\+\\+$",
      "endCaptures": {
        "0": {
          "name": "punctuation.section.embedded.end.hugo"
        }
      },
      "patterns": [
        {
          "match": "\\b([^\\s^\\\"]+)\\b",
          "name": "constant.character.hugo"
        },
        {
          "begin": "'",
          "end": "'",
          "name": "string.quoted.single.hugo"
        },
        {
          "begin": "\"",
          "end": "\"",
          "name": "string.quoted.single.hugo"
        }
      ]
    }
  ],
  "scopeName": "source.hugo"
}</code></pre>
</details>

**Comment by budparr** [comment]
Thanks for doing that, @jhabdas. I spent a few hours on this some weeks ago and got nowhere.

**Comment by ghost** [comment]
@mattstratton think you could tag this help wanted? I'll consider putting a bounty on it, made payable in cryptocurrency.

**Comment by jhabdas** [comment]
Thanks! Also, pretty sure I borked something in my JSON while converting the regular expressions. I've adjusted the comment above to make a note of it.

**Comment by lichtner** [comment]
Still not working. I think it is the same issue as spellcheck, which doesn't work too. I added an issue for spellcheck here #13. Maybe this package is not correctly integrated with other Atom packages.
